export const trips = [
  {
    id: 'forbidden-tour',
    title: 'Forbidden Tour',
    category: 'Ski & Splitboard',
    location: 'North Cascades, WA',
    duration: '4 Days',
    durationDays: 4,
    difficulty: 'Expert',
    price: 1395,
    spotsLeft: 3,
    season: 'Spring',
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1600&q=90',
    gallery: [
      'https://images.unsplash.com/photo-1516592673884-4a382d1124c2?w=800&q=80',
      'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=80',
      'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&q=80',
      'https://images.unsplash.com/photo-1502126324834-38f8e02d7160?w=800&q=80',
    ],
    dates: ['April 18–21, 2026', 'Custom Dates Available'],
    ratio: '3:1',
    included: 'All meals on mountain, tents, stoves, cook kits, group climbing equipment, guide services',
    notIncluded: 'Ground transportation, airfare, hotel accommodations, gratuities, personal items',
    shortDesc: 'The Cascades answer to the Haute Route. Traverse Forbidden, Klawatti and Eldorado Peaks across 3 passes with 3–4,000 ft descents.',
    longDesc: 'The North Cascades in spring offer the best high alpine touring in the Lower 48. Starting in Boston Basin, we traverse some of the largest glaciers in the Cascades, circumnavigating Forbidden, Klawatti and Eldorado Peaks crossing 3 passes with several 3-4,000 foot descents along the way.',
    itinerary: [
      { day: 1, title: 'Boston Basin Approach', stats: '4,400ft up · ~5 Miles · 6-7 hrs', description: 'After a 6:30am orientation in Seattle, we drive to the North Cascades and approach Boston Basin. We ascend to high camp at ~6,000 feet — one of the most visually striking camps in the range, with towering granite faces and hanging glaciers.' },
      { day: 2, title: 'Forbidden Glacier Descent', stats: '1,200ft up / 4,000ft down · ~4 Miles · 4-6 hrs', description: 'We climb toward Sharkfin Col, traverse the upper Boston Glacier beneath the north face of Forbidden Peak, then drop onto the Forbidden Glacier for a 4,000-foot descent to Moraine Lake.' },
      { day: 3, title: 'Up to the Inspiration Glacier', stats: '4,300ft up · ~5 Miles · 6-7 hrs', description: 'From Moraine Lake we ascend the remote Inspiration Glacier to Klawatti Col with expansive views. Afternoon options include skiing the McAllister Glacier or snow skills practice.' },
      { day: 4, title: 'Eldorado Summit & Exit', stats: '1,200ft up / 6,800ft down · ~5 Miles · 6-8 hrs', description: 'Summit Eldorado Peak at 8,868ft and ski directly off the summit — an unforgettable descent of massive glaciated terrain into Eldorado Creek. A grand finale to one of the finest ski circuits in the PNW.' },
    ],
    tags: ['ski-mountaineering', 'traverse'],
    bookingUrl: '#',
  },
  {
    id: 'steep-camp',
    title: 'Steep Camp',
    category: 'Ski & Splitboard',
    location: 'North Cascades, WA',
    duration: '3 Days',
    durationDays: 3,
    difficulty: 'Advanced',
    price: 975,
    spotsLeft: 5,
    season: 'Winter',
    image: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=1600&q=90',
    gallery: [],
    dates: ['January–March 2026', 'Multiple Dates'],
    ratio: '4:1',
    included: 'Instruction, group safety equipment, guide services',
    notIncluded: 'Personal gear, meals, transportation, lodging',
    shortDesc: 'Master steep and technical terrain with focused coaching from IFMGA guides. Small groups, maximum progression.',
    longDesc: 'Intro to Steep & Technical Riding is designed for advanced skiers and riders ready to push into more committing terrain with proper skills and safety knowledge. Over three days, you will work with IFMGA-certified guides on technique, fall arrest, skiing judgment, and exposure management in steep lines.',
    itinerary: [
      { day: 1, title: 'Skills Assessment & Technique', stats: '2,000ft · 4-5 hrs', description: 'We begin with a skills assessment on moderate steep terrain, then focus on fundamental technique drills: edge engagement, countering, and turn initiation in steep terrain.' },
      { day: 2, title: 'Steep Lines & Judgment', stats: '2,500ft · 5-6 hrs', description: 'Progress to steeper terrain with a focus on reading snow conditions, line choice, and consequence management. Guides coach in real time from strategic positions.' },
      { day: 3, title: 'Capstone Objective', stats: '3,000ft · 6-7 hrs', description: 'Apply everything learned on a significant steep objective chosen based on current conditions and group ability.' },
    ],
    tags: ['steep-skiing', 'course'],
    bookingUrl: '#',
  },
  {
    id: 'aiare-level-1',
    title: 'AIARE Level 1 Avalanche Course',
    category: 'Avalanche',
    location: 'Washington Cascades',
    duration: '3 Days',
    durationDays: 3,
    difficulty: 'Beginner',
    price: 650,
    spotsLeft: 8,
    season: 'Winter',
    image: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=1600&q=90',
    gallery: [],
    dates: ['January–March 2026', 'Multiple Dates'],
    ratio: '4:1',
    included: 'Course materials, guide instruction, group safety gear',
    notIncluded: 'Personal avalanche beacon, probe, shovel, meals, lodging',
    shortDesc: 'The gold standard in recreational avalanche education. Learn to travel safely in avalanche terrain.',
    longDesc: 'The AIARE Level 1 is the most widely recognized avalanche course in North America, covering terrain assessment, snowpack evaluation, rescue techniques, and safe travel protocols. Upon completion, participants will have the knowledge and skills to make informed decisions and travel more safely in avalanche terrain.',
    itinerary: [
      { day: 1, title: 'Avalanche Fundamentals (Classroom)', stats: 'Evening session · 3 hrs', description: 'Introduction to avalanche formation, terrain recognition, weather, and snowpack. Review forecasting resources and the ATES terrain classification system.' },
      { day: 2, title: 'Field Day 1 — Terrain & Snowpack', stats: 'Full day · 6-7 hrs', description: 'Hands-on terrain evaluation, snow pit analysis, stability tests, and group management protocols in real avalanche terrain.' },
      { day: 3, title: 'Field Day 2 — Rescue', stats: 'Full day · 6-7 hrs', description: 'Beacon search patterns, probe technique, strategic shoveling, and simulated rescue scenarios. Trip planning and decision-making review.' },
    ],
    tags: ['avalanche', 'safety', 'course'],
    bookingUrl: '#',
  },
  {
    id: 'chamonix-climbing',
    title: 'Chamonix — French Alps Climbing',
    category: 'Alpine',
    location: 'Chamonix, France',
    duration: '8 Days',
    durationDays: 8,
    difficulty: 'Advanced',
    price: 3200,
    spotsLeft: 2,
    season: 'Summer',
    image: 'https://images.unsplash.com/photo-1502126324834-38f8e02d7160?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1502126324834-38f8e02d7160?w=1600&q=90',
    gallery: [],
    dates: ['July 5–12, 2026', 'August 2–9, 2026'],
    ratio: '2:1',
    included: 'Guide services, hut fees, group technical equipment',
    notIncluded: 'Flights, transfers, meals, personal gear, travel insurance (required)',
    shortDesc: "Climb classics in one of the world's greatest alpine playgrounds. Aiguilles, aretes, and glaciers with IFMGA guides.",
    longDesc: 'Climb the iconic routes of the Mont Blanc massif with IFMGA certified guides who know the range intimately. From the granite spires of the Aiguilles to the high glaciated faces of the massif, this program is designed to take skilled mountaineers on the routes that define alpine climbing.',
    itinerary: [
      { day: 1, title: 'Arrive Chamonix', stats: 'Orientation day', description: 'Gear check, introductions, and acclimatization walk above Chamonix. Strategy session for the week based on current conditions.' },
      { day: 2, title: 'Rock Skills Day', stats: 'Aiguilles Training Area · 6-7 hrs', description: 'Warm up on excellent granite in the Aiguilles training areas, calibrating systems and technique for the bigger objectives ahead.' },
      { day: 3, title: 'Cosmiques Ridge', stats: '3,842m summit · 7-9 hrs', description: 'A classic acclimatization route with magnificent views. Overnight at the Cosmiques Refuge.' },
      { day: 4, title: 'Rest / Acclimatization', stats: 'Flexible day', description: 'Rest, gear prep, and optional easier objectives based on team fitness and conditions.' },
      { day: 5, title: 'Aiguille du Chardonnet', stats: 'Forbes Arête · 3,824m · Full day', description: 'One of the great mixed ridges of the Alps. Technical, sustained, and spectacular.' },
      { day: 6, title: 'Rest Day', stats: 'Chamonix valley', description: 'Recovery day in Chamonix. Optional via ferrata or equipment day.' },
      { day: 7, title: 'Main Objective', stats: 'Condition dependent', description: 'Tackle the headline objective of the trip — Mont Blanc, the Frendo Spur, or the Ryan-Lochmatter depending on conditions and team ability.' },
      { day: 8, title: 'Depart', stats: 'Departure day', description: 'Final breakfast together in Chamonix. Transfers to Geneva airport.' },
    ],
    tags: ['alpine', 'international', 'climbing'],
    bookingUrl: '#',
  },
  {
    id: 'morning-star-peak',
    title: 'Morning Star Peak — Mile High Club',
    category: 'Rock',
    location: 'North Cascades, WA',
    duration: '1 Day',
    durationDays: 1,
    difficulty: 'Intermediate',
    price: 425,
    spotsLeft: 6,
    season: 'Summer',
    image: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=1600&q=90',
    gallery: [],
    dates: ['June–September 2026'],
    ratio: '2:1',
    included: 'Guide services, group climbing equipment, technical gear',
    notIncluded: 'Personal gear, meals, transportation',
    shortDesc: 'A stunning multi-pitch rock climb on beautiful Cascade granite. II+ 5.10a. One of the best moderate climbs in the range.',
    longDesc: 'The Mile High Club on Morning Star Peak is a classic North Cascades multi-pitch route on excellent granite with spectacular views of the surrounding peaks. At II+ 5.10a, the route offers sustained, engaging climbing accessible to motivated intermediate climbers.',
    itinerary: [
      { day: 1, title: 'Approach, Climb & Descent', stats: '8 pitches · 5.10a · 10-12 hrs total', description: 'Early morning drive to the trailhead, hike through old-growth forest to the base, climb 8 pitches of beautiful granite, summit, and descend via rappel.' },
    ],
    tags: ['rock-climbing', 'multi-pitch'],
    bookingUrl: '#',
  },
  {
    id: 'alaska-ski-mo',
    title: 'Alaska Range Ski Mo Camp',
    category: 'Ski & Splitboard',
    location: 'Alaska Range, AK',
    duration: '10 Days',
    durationDays: 10,
    difficulty: 'Expert',
    price: 4800,
    spotsLeft: 4,
    season: 'Spring',
    image: 'https://images.unsplash.com/photo-1516592673884-4a382d1124c2?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1516592673884-4a382d1124c2?w=1600&q=90',
    gallery: [],
    dates: ['April 20–29, 2026'],
    ratio: '3:1',
    included: 'Fly-in, all meals, camp equipment, guide services',
    notIncluded: 'Flights to Anchorage, personal gear, travel insurance (required)',
    shortDesc: 'Glacier skiing in the heart of the Alaska Range. Big objectives, remote camps, unforgettable descents.',
    longDesc: 'An expedition-style ski mountaineering camp deep in the Alaska Range. Access glaciers by bush plane and ski massive remote terrain for 10 days. This is the real deal — crevassed glaciers, Alaskan weather, and descents measured in thousands of vertical feet on terrain that few will ever see.',
    itinerary: [
      { day: 1, title: 'Anchorage & Talkeetna', stats: 'Drive/fly to Talkeetna', description: 'Arrive Anchorage, drive to Talkeetna for final gear check and weather briefing.' },
      { day: 2, title: 'Fly-In to Base Camp', stats: 'Bush plane · 30 min flight', description: 'Fly onto the glacier with Talkeetna Air Taxi. Establish base camp and acclimate to the environment.' },
      { day: 3, title: 'Camp Ski & Scouting', stats: '3,000ft · 5-6 hrs', description: 'Calibrate to the glacier and ski the terrain immediately surrounding camp. Scout objectives for the week.' },
      { day: 4, title: 'First Major Objective', stats: 'Condition dependent · Full day', description: 'Tackle the first large ski objective of the trip — a 5,000+ foot descent on a major glaciated face.' },
      { day: 5, title: 'Rest / Exploration Day', stats: 'Flexible', description: 'Active rest, explore side glaciers, photography, and preparation for upcoming objectives.' },
      { day: 6, title: 'High Camp Push', stats: '5,000ft · 6-8 hrs', description: 'Establish a high camp for access to the biggest terrain on the trip.' },
      { day: 7, title: 'Summit Objective', stats: '2,000ft up / 6,000ft down · Full day', description: 'Summit attempt on a major Alaska Range peak. Long descent to base camp.' },
      { day: 8, title: 'Weather Day / Bonus Objective', stats: 'Flexible', description: 'Ski bonus terrain or rest depending on weather and energy levels.' },
      { day: 9, title: 'Final Big Day', stats: 'Full day', description: 'Last major objective. Make the most of the remaining time on the glacier.' },
      { day: 10, title: 'Fly Out & Celebrate', stats: 'Bush plane out', description: 'Break camp, fly back to Talkeetna, and celebrate an unforgettable 10 days in one of the world\'s great mountain ranges.' },
    ],
    tags: ['ski-mountaineering', 'alaska', 'expedition'],
    bookingUrl: '#',
  },
  {
    id: 'aiare-level-2',
    title: 'AIARE Level 2 Course',
    category: 'Avalanche',
    location: 'Washington Cascades',
    duration: '4 Days',
    durationDays: 4,
    difficulty: 'Intermediate',
    price: 950,
    spotsLeft: 6,
    season: 'Winter',
    image: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&q=85',
    heroImage: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=1600&q=90',
    gallery: [],
    dates: ['January–March 2026', 'Multiple Dates'],
    ratio: '4:1',
    included: 'Course materials, guide instruction, group safety gear',
    notIncluded: 'Personal avalanche beacon, probe, shovel, meals, lodging',
    shortDesc: 'Advanced avalanche decision-making for experienced backcountry travelers and guides.',
    longDesc: 'The AIARE Level 2 is designed for experienced backcountry travelers seeking to develop advanced decision-making skills and lead groups in complex avalanche terrain. Prerequisites: AIARE Level 1, 20+ days backcountry experience.',
    itinerary: [
      { day: 1, title: 'Review & Advanced Snowpack', stats: 'Full day field', description: 'Review Level 1 concepts and dive deep into advanced snowpack assessment, including weak layer identification and spatial variability.' },
      { day: 2, title: 'Terrain Management', stats: 'Full day field', description: 'Advanced terrain selection for group leaders, exposure management, and leadership decision frameworks.' },
      { day: 3, title: 'Complex Terrain & Rescue', stats: 'Full day field', description: 'Managing rope teams in complex terrain, extended rescue scenarios, and multi-burial exercises.' },
      { day: 4, title: 'Guided Ski Tour & Assessment', stats: 'Full day field', description: 'Students lead a full touring day with real-time instructor feedback. Written and practical assessments.' },
    ],
    tags: ['avalanche', 'safety', 'course', 'leadership'],
    bookingUrl: '#',
  },
  {
    id: 'aiare-rescue',
    title: 'AIARE Rescue Course',
    category: 'Avalanche',
    location: 'Washington Cascades',
    duration: '1 Day',
    durationDays: 1,
    difficulty: 'Beginner',
    price: 225,
    spotsLeft: 10,
    season: 'Winter',
    image: 'https://images.unsplash.com/photo-1516592673884-4a382d1124c2?w=800&q=85',
    heroImage: 'https://images.unsplash.com/photo-1516592673884-4a382d1124c2?w=1600&q=90',
    gallery: [],
    dates: ['January–March 2026', 'Multiple Dates'],
    ratio: '4:1',
    included: 'Instruction, practice beacons and probes available for use',
    notIncluded: 'Personal avalanche beacon, probe, shovel',
    shortDesc: 'Focused companion rescue training. Beacon searches, probing strategy, and efficient shoveling techniques.',
    longDesc: 'A focused one-day course covering the complete companion rescue sequence. Practice beacon searches, efficient probing patterns, and advanced shoveling strategies. This course is suitable for all backcountry travelers regardless of experience level.',
    itinerary: [
      { day: 1, title: 'Full Rescue Course', stats: '6-7 hrs', description: 'Morning: beacon fundamentals, single and multi-burial signal searches. Afternoon: probing technique, strategic shoveling, simulated full rescue scenarios under time pressure.' },
    ],
    tags: ['avalanche', 'rescue', 'safety'],
    bookingUrl: '#',
  },
  {
    id: 'dorado-needle',
    title: 'Dorado Needle — NW Ridge',
    category: 'Alpine',
    location: 'North Cascades, WA',
    duration: '2 Days',
    durationDays: 2,
    difficulty: 'Intermediate',
    price: 750,
    spotsLeft: 4,
    season: 'Summer',
    image: 'https://images.unsplash.com/photo-1502126324834-38f8e02d7160?w=800&q=85',
    heroImage: 'https://images.unsplash.com/photo-1502126324834-38f8e02d7160?w=1600&q=90',
    gallery: [],
    dates: ['June–September 2026'],
    ratio: '2:1',
    included: 'Guide services, group technical equipment, rack',
    notIncluded: 'Personal gear, meals, transportation',
    shortDesc: 'A stunning two-day alpine objective in the heart of the Cascades on perfect granite.',
    longDesc: 'The Northwest Ridge of Dorado Needle is one of the most aesthetic two-day alpine objectives in the North Cascades. Beautiful granite climbing leads to a stunning summit perched above the Eldorado Glacier with sweeping views of the Cascades in every direction.',
    itinerary: [
      { day: 1, title: 'Approach & Bivy', stats: '~6 Miles · 3,500ft · 5-7 hrs', description: 'Hike through old-growth forest and alpine meadows to a high bivy below the route. Spectacular sunset views over the range.' },
      { day: 2, title: 'Summit & Return', stats: '2,000ft climbing · 10-12 hrs', description: 'Climb the Northwest Ridge on excellent granite, summit Dorado Needle, and descend via rappel back to the valley.' },
    ],
    tags: ['alpine', 'rock-climbing', 'north-cascades'],
    bookingUrl: '#',
  },
  {
    id: 'forbidden-peak',
    title: 'Forbidden Peak — East Ridge',
    category: 'Alpine',
    location: 'North Cascades, WA',
    duration: '2 Days',
    durationDays: 2,
    difficulty: 'Advanced',
    price: 850,
    spotsLeft: 3,
    season: 'Summer',
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=85',
    heroImage: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1600&q=90',
    gallery: [],
    dates: ['July 5–7, 2026', 'August 8–10, 2026'],
    ratio: '2:1',
    included: 'Guide services, group technical equipment, glacier travel gear',
    notIncluded: 'Personal gear, meals, transportation',
    shortDesc: 'One of the finest alpine routes in North America. III 5.8. Exposed ridge climbing on perfect granite.',
    longDesc: 'The East Ridge of Forbidden Peak (8,815ft) is widely regarded as one of the finest alpine routes in North America — a sustained, exposed ridge culminating in a sensational summit with views across the Cascade Range. Rated III 5.8, the route combines technical rock with glacier travel and is a true North Cascades classic.',
    itinerary: [
      { day: 1, title: 'Boston Basin Camp', stats: '4,400ft · ~5 Miles · 5-6 hrs', description: 'Drive to the trailhead and hike to high camp in beautiful Boston Basin beneath the north face of Forbidden Peak.' },
      { day: 2, title: 'East Ridge & Summit', stats: '3,500ft up/down · 7-9 hrs', description: 'Rope up at dawn and climb the classic East Ridge (III 5.8) to the summit at 8,815ft. Descend via the Quien Sabe Glacier back to camp and out to the car.' },
    ],
    tags: ['alpine', 'climbing', 'north-cascades'],
    bookingUrl: '#',
  },
  {
    id: 'snoqualmie-ski',
    title: 'Snoqualmie Pass Ski Tours',
    category: 'Ski & Splitboard',
    location: 'Snoqualmie Pass, WA',
    duration: '1 Day',
    durationDays: 1,
    difficulty: 'Beginner',
    price: 295,
    spotsLeft: 8,
    season: 'Winter',
    image: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=85',
    heroImage: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=1600&q=90',
    gallery: [],
    dates: ['January–March 2026', 'Multiple Weekends'],
    ratio: '4:1',
    included: 'Guide services, avalanche safety instruction, group safety equipment',
    notIncluded: 'Ski or splitboard gear, avalanche safety gear, meals',
    shortDesc: 'Perfect intro to backcountry skiing. Local terrain, accessible objectives, expert guidance just 45 minutes from Seattle.',
    longDesc: 'The best way to start your backcountry skiing journey. Using the accessible terrain around Snoqualmie Pass, this one-day program covers skinning technique, route-finding, basic avalanche awareness, and the fundamentals of safe backcountry travel — all just 45 minutes from Seattle.',
    itinerary: [
      { day: 1, title: 'Full Day Intro Tour', stats: '1,500–2,500ft · 4-6 hrs', description: 'Meet at the trailhead, learn to skin, practice terrain assessment, and ski a beautiful tour with IFMGA-certified guides. Perfect for resort skiers making their first steps into the backcountry.' },
    ],
    tags: ['backcountry-skiing', 'intro', 'beginner'],
    bookingUrl: '#',
  },
  {
    id: 'haute-route',
    title: 'Haute Route',
    category: 'Ski & Splitboard',
    location: 'Swiss Alps',
    duration: '7 Days',
    durationDays: 7,
    difficulty: 'Advanced',
    price: 3800,
    spotsLeft: 4,
    season: 'Spring',
    image: 'https://images.unsplash.com/photo-1502126324834-38f8e02d7160?w=800&q=85',
    heroImage: 'https://images.unsplash.com/photo-1502126324834-38f8e02d7160?w=1600&q=90',
    gallery: [],
    dates: ['April 5–11, 2026', 'April 19–25, 2026'],
    ratio: '4:1',
    included: 'Hut fees, guide services, group equipment',
    notIncluded: 'Flights to Geneva, transfers, personal gear, meals in huts, travel insurance (required)',
    shortDesc: 'The original hut-to-hut ski traverse. Chamonix to Zermatt — the route that started it all.',
    longDesc: 'The Haute Route from Chamonix to Zermatt is the most famous ski traverse in the world — seven days crossing some of the most spectacular high alpine terrain in the Alps. Passing beneath the north faces of the great peaks, sleeping in mountain huts, and skiing sustained descents day after day, the Haute Route is a bucket-list experience for any serious ski tourer.',
    itinerary: [
      { day: 1, title: 'Chamonix → Argentière Refuge', stats: '1,600m descent · 4-5 hrs skiing', description: 'Acclimatize in Chamonix, take the cable car and begin the traverse with a beautiful descent to the Argentière Glacier.' },
      { day: 2, title: 'Argentière → Trient Refuge', stats: '1,800m up / 1,600m down · 6-8 hrs', description: 'Cross the Fenêtre de Saleinaz, one of the classic high passes of the route, with sweeping views of the Chamonix Aiguilles.' },
      { day: 3, title: 'Trient → Champex or Verbier', stats: 'Flexible day', description: 'Descent through beautiful terrain to the Rhône Valley and transfer to Verbier for the night.' },
      { day: 4, title: 'Verbier → Cabane du Dix', stats: '1,400m up / 1,200m down · 6-7 hrs', description: 'Classic Haute Route day crossing the Col de Prafleuri with views of the Grand Combin.' },
      { day: 5, title: 'Cabane du Dix → Arolla', stats: '1,600m down · 4-5 hrs', description: 'Big descent day — ski the vast slopes below the Dix Glacier into the beautiful Arolla Valley.' },
      { day: 6, title: 'Arolla → Zinal or Schönbiel Hut', stats: '1,400m up / 1,200m down · 6-7 hrs', description: 'Cross the Col de Riedmatten, a demanding high pass with spectacular views toward the Matterhorn.' },
      { day: 7, title: 'Schönbiel → Zermatt', stats: '2,200m descent · 4-5 hrs', description: 'The grand finale — a magnificent descent off the Stockji Glacier into Zermatt with the Matterhorn towering overhead.' },
    ],
    tags: ['ski-touring', 'hut-to-hut', 'international', 'traverse'],
    bookingUrl: '#',
  },
  {
    id: 'rogers-pass',
    title: 'Rogers Pass Adventure Week',
    category: 'Ski & Splitboard',
    location: 'Rogers Pass, BC',
    duration: '7 Days',
    durationDays: 7,
    difficulty: 'Advanced',
    price: 2600,
    spotsLeft: 5,
    season: 'Winter',
    image: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&q=85',
    heroImage: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=1600&q=90',
    gallery: [],
    dates: ['February 14–20, 2026', 'March 7–13, 2026'],
    ratio: '4:1',
    included: 'Guide services, hut fees for 4 nights, group safety equipment',
    notIncluded: 'Travel to Golden BC, personal ski gear, avalanche kit, some meals',
    shortDesc: "Canada's backcountry ski mecca. Deep Selkirk powder and dramatic mountain terrain.",
    longDesc: "Rogers Pass in the Selkirk Mountains of British Columbia is North America's premier backcountry ski destination. Cold, dry powder, dramatic terrain, and a mix of hut-based travel make this a world-class experience for advanced ski tourers.",
    itinerary: [
      { day: 1, title: 'Arrive Golden / Orientation', stats: 'Drive to Rogers Pass', description: 'Meet in Golden, BC, drive to the pass, gear check, and orientation briefing.' },
      { day: 2, title: 'Balu Pass Area', stats: '2,200ft · 5-6 hrs', description: 'Classic introductory day touring the Balu Pass area with spectacular views and reliable powder skiing.' },
      { day: 3, title: 'Hike Into Hut', stats: '3,000ft · 6-7 hrs', description: 'Skin into the first of our overnight huts through spectacular old-growth forest and alpine terrain.' },
      { day: 4, title: 'Hut-Based Big Day', stats: '3,500ft · 7-8 hrs', description: 'The best day of the trip — access remote terrain only reachable from the hut with huge descents.' },
      { day: 5, title: 'Second Hut Move', stats: '2,500ft · 6-7 hrs', description: 'Traverse to the second hut via a high col, skiing continuous descent on the far side.' },
      { day: 6, title: 'Remote Terrain Day', stats: '3,000ft · 7-8 hrs', description: 'Explore the most remote zones of the permit area with first-tracks powder on untouched slopes.' },
      { day: 7, title: 'Exit & Drive Out', stats: '2,500ft down · 4-5 hrs', description: 'Final touring day skiing back to the highway and driving to Golden for hot showers and celebration.' },
    ],
    tags: ['backcountry-skiing', 'canada', 'hut-to-hut', 'powder'],
    bookingUrl: '#',
  },
  {
    id: 'japan-powder',
    title: 'Japan — Zen of Powder',
    category: 'Ski & Splitboard',
    location: 'Niseko, Japan',
    duration: '10 Days',
    durationDays: 10,
    difficulty: 'Intermediate',
    price: 3400,
    spotsLeft: 6,
    season: 'Winter',
    image: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=85',
    heroImage: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=1600&q=90',
    gallery: [],
    dates: ['January 15–24, 2026', 'February 5–14, 2026'],
    ratio: '5:1',
    included: 'Guide services, 9 nights lodging, most meals, onsen access, cultural activities',
    notIncluded: 'Flights to Hokkaido, ski lift tickets, personal gear, travel insurance (required), some meals',
    shortDesc: 'Legendary Hokkaido powder with Japanese culture, onsen, and incredible food.',
    longDesc: "Hokkaido receives more snowfall than almost anywhere on Earth — light, dry, seemingly never-ending powder. Combined with Japan's incredible hospitality, food, and culture, this 10-day program is as much a cultural experience as a ski trip. We combine in-bounds powder days at Niseko with off-piste touring in the surrounding mountains.",
    itinerary: [
      { day: 1, title: 'Arrive Sapporo', stats: 'Arrival day', description: 'Arrive Sapporo, transfer to Niseko. Welcome dinner and program overview.' },
      { day: 2, title: 'Niseko In-Bounds', stats: 'Full day resort', description: 'Warm up day skiing in-bounds at Niseko Grand Hirafu. Learn the mountain layout and ski with your guide.' },
      { day: 3, title: 'Backcountry Day 1', stats: '1,500ft · 5-6 hrs', description: 'First backcountry day skinning above the resort boundary into the pristine Hokkaido powder fields.' },
      { day: 4, title: 'Mt. Yōtei Approach', stats: 'Base camp day', description: 'Drive to the Yōtei area, ski the volcano flanks, and explore Kyogoku town for hot springs and soba.' },
      { day: 5, title: 'Mt. Yōtei Ski Tour', stats: '3,200ft · 6-8 hrs', description: 'The crown jewel of Hokkaido ski touring — ski the perfect cone of Mt. Yōtei on deep powder.' },
      { day: 6, title: 'Rest & Onsen Day', stats: 'Cultural day', description: 'Soak in Niseko\'s famous hot springs, explore local villages, and rest for the second half of the trip.' },
      { day: 7, title: 'Rusutsu Resort & Backcountry', stats: 'Full day', description: 'Drive to Rusutsu for a day of diverse terrain — resort powder and guided backcountry access.' },
      { day: 8, title: 'Kiroro Backcountry', stats: '2,500ft · 6-7 hrs', description: 'Explore the deep forests and wide-open powder faces around Kiroro — some of the best skiing in Japan.' },
      { day: 9, title: 'Niseko Gates & Final Big Day', stats: '3,000ft · 6-8 hrs', description: 'Full day skiing the best terrain of the trip with deep powder and maximum fun.' },
      { day: 10, title: 'Sapporo & Farewell', stats: 'Departure day', description: 'Morning check-out, drive to Sapporo, farewell lunch, transfer to airport.' },
    ],
    tags: ['backcountry-skiing', 'international', 'powder', 'japan'],
    bookingUrl: '#',
  },
  {
    id: 'womens-ski-alpinism',
    title: "Women's Intro to Ski Alpinism",
    category: "Women's Programs",
    location: 'North Cascades, WA',
    duration: '3 Days',
    durationDays: 3,
    difficulty: 'Intermediate',
    price: 875,
    spotsLeft: 7,
    season: 'Spring',
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=85',
    heroImage: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1600&q=90',
    gallery: [],
    dates: ['April 4–6, 2026', 'April 25–27, 2026'],
    ratio: '4:1',
    included: 'Guide services, group equipment, in-field instruction',
    notIncluded: 'Personal ski mountaineering gear, meals, transportation, lodging',
    shortDesc: "Women-specific ski mountaineering. Build confidence and community in a supportive mountain environment.",
    longDesc: "A three-day women-specific program introducing ski mountaineering techniques in a supportive, empowering environment. This program is designed to help women develop the technical skills and mountain judgment to take on bigger objectives — and to build community with other women who love the mountains.",
    itinerary: [
      { day: 1, title: 'Skinning & Route-Finding', stats: '1,500ft · ~4 Miles · 4-5 hrs', description: 'Introduction to uphill travel, skinning technique, reading terrain, and basic glacier travel. Focus on building confidence and fluency with the gear.' },
      { day: 2, title: 'Glacier Skills & Steep Terrain', stats: '2,500ft up · ~5 Miles · 6-7 hrs', description: 'Rope travel, crevasse awareness, crampon and ice axe technique, and skiing moderate steep terrain with proper skills.' },
      { day: 3, title: 'Peak Objective', stats: '3,000ft up / 3,000ft down · 6-8 hrs', description: 'Apply all skills to summit a North Cascades peak. A celebration of everything learned over three days, with epic views as the reward.' },
    ],
    tags: ['ski-mountaineering', 'womens-program', 'course'],
    bookingUrl: '#',
  },
  {
    id: 'crevasse-rescue',
    title: 'Crevasse Rescue Seminar',
    category: 'Alpine',
    location: 'North Cascades, WA',
    duration: '1 Day',
    durationDays: 1,
    difficulty: 'Intermediate',
    price: 295,
    spotsLeft: 9,
    season: 'Summer',
    image: 'https://images.unsplash.com/photo-1516592673884-4a382d1124c2?w=800&q=85',
    heroImage: 'https://images.unsplash.com/photo-1516592673884-4a382d1124c2?w=1600&q=90',
    gallery: [],
    dates: ['June–September 2026', 'Multiple Dates'],
    ratio: '4:1',
    included: 'Guide services, group rope and rescue hardware',
    notIncluded: 'Personal glacier travel gear, harness, crampons, ice axe',
    shortDesc: 'Essential skills for glacier travel. Learn crevasse rescue and safe rope team movement.',
    longDesc: 'An essential one-day course for anyone venturing onto glaciated terrain. Learn to build bomb-proof anchors, execute efficient crevasse rescues using Z-pulleys, and travel safely as a roped team on a real North Cascades glacier.',
    itinerary: [
      { day: 1, title: 'Glacier Rescue Full Day', stats: '3,000ft · 7-8 hrs', description: 'Morning: hike to glacier, rope team travel, self-arrest, anchor building. Afternoon: full crevasse rescue practice using Z-pulley and drop-C systems. Multiple simulated rescue scenarios.' },
    ],
    tags: ['glacier-travel', 'crevasse-rescue', 'alpine-skills'],
    bookingUrl: '#',
  },
]

export const guides = [
  {
    id: 'ian-nicholson',
    name: 'Ian Nicholson',
    title: 'IFMGA / AMGA Mountain Guide',
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&q=80',
    specialties: ['Alpine Climbing', 'Ski Mountaineering', 'Rock Climbing'],
    yearsGuiding: 20,
    bio: 'Ian has spent over two decades guiding in the Cascades, Alps, Andes, and ranges across the globe. He holds the highest international guiding certification (IFMGA) and has authored guidebooks to the region.',
    certifications: ['IFMGA', 'AMGA Rock', 'AMGA Alpine', 'AMGA Ski', 'WFR'],
    highlights: ['First ascents in the North Cascades', 'AMGA Guide Trainer', 'Published guidebook author'],
  },
  {
    id: 'matt-schonwald',
    name: 'Matt Schonwald',
    title: 'IFMGA / AMGA Mountain Guide',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80',
    specialties: ['Backcountry Skiing', 'Alpine Climbing', 'Avalanche Education'],
    yearsGuiding: 18,
    bio: 'Matt brings 18 years of high-altitude experience across four continents. A passionate educator, he trains guides through the AMGA and has led expeditions from Patagonia to the Himalayas.',
    certifications: ['IFMGA', 'AMGA Ski', 'AMGA Alpine', 'AIARE Pro', 'WFR'],
    highlights: ['Himalayan expedition leader', 'AMGA examiner', 'Avalanche educator'],
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Sarah K.',
    location: 'Seattle, WA',
    trip: 'Forbidden Tour',
    rating: 5,
    quote: "The Forbidden Tour was the single best week of my life. Ian and the team made an incredibly demanding route feel achievable. The views from Eldorado's summit brought me to tears.",
    image: 'https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=100&q=80',
  },
  {
    id: 2,
    name: 'Marcus T.',
    location: 'Portland, OR',
    trip: 'AIARE Level 1',
    rating: 5,
    quote: 'Matt is an exceptional educator. The AIARE course changed how I think about backcountry travel. Worth every penny — this knowledge could save your life.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
  },
  {
    id: 3,
    name: 'Julia R.',
    location: 'Denver, CO',
    trip: 'Chamonix Climbing',
    rating: 5,
    quote: 'Summiting in the French Alps with BCAG was a bucket list moment. The guides expertise and local knowledge made it both safe and deeply memorable.',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
  },
  {
    id: 4,
    name: 'David L.',
    location: 'San Francisco, CA',
    trip: 'Steep Camp',
    rating: 5,
    quote: "I've skied with a lot of guides over the years. BCAG is operating at a completely different level — technically, educationally, and in terms of the experience they create.",
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
  },
]

export const stats = [
  { value: '20+', label: 'Years Guiding' },
  { value: 'IFMGA', label: 'Certified Guides' },
  { value: '500+', label: 'Happy Clients' },
  { value: '4', label: 'Continents' },
]
