export const trips = [
  {
    id: 'forbidden-tour',
    title: 'Forbidden Tour',
    category: 'Ski & Splitboard',
    location: 'North Cascades, WA',
    duration: '4 Days',
    difficulty: 'Expert',
    price: 1395,
    spotsLeft: 3,
    season: 'Spring',
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1600&q=90',
    gallery: [
      'https://images.unsplash.com/photo-1516592673884-4a382d1124c2?w=800&q=80',
      'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=80',
      'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&q=80',
      'https://images.unsplash.com/photo-1502126324834-38f8e02d7160?w=800&q=80',
    ],
    dates: ['April 18–21, 2026', 'Custom Dates Available'],
    ratio: '3:1',
    included: 'All meals on mountain, tents, stoves, cook kits, group climbing equipment, guide services',
    notIncluded: 'Ground transportation, airfare, hotel accommodations, gratuities, personal items',
    shortDesc: 'The Cascades answer to the Haute Route. Traverse Forbidden, Klawatti and Eldorado Peaks across 3 passes with 3–4,000 ft descents.',
    longDesc: 'The North Cascades in spring offer the best high alpine touring in the Lower 48. Starting in Boston Basin, we traverse some of the largest glaciers in the Cascades, circumnavigating Forbidden, Klawatti and Eldorado Peaks crossing 3 passes with several 3-4,000 foot descents along the way.',
    itinerary: [
      { day: 1, title: 'Boston Basin Approach', stats: '4,400ft up · ~5 Miles · 6-7 hrs', description: 'After a 6:30am orientation in Seattle, we drive to the North Cascades and approach Boston Basin. We ascend to high camp at ~6,000 feet — one of the most visually striking camps in the range, with towering granite faces and hanging glaciers.' },
      { day: 2, title: 'Forbidden Glacier Descent', stats: '1,200ft up / 4,000ft down · ~4 Miles · 4-6 hrs', description: 'We climb toward Sharkfin Col, traverse the upper Boston Glacier beneath the north face of Forbidden Peak, then drop onto the Forbidden Glacier for a 4,000-foot descent to Moraine Lake.' },
      { day: 3, title: 'Up to the Inspiration Glacier', stats: '4,300ft up · ~5 Miles · 6-7 hrs', description: 'From Moraine Lake we ascend the remote Inspiration Glacier to Klawatti Col with expansive views. Afternoon options include skiing the McAllister Glacier or snow skills practice.' },
      { day: 4, title: 'Eldorado Summit & Exit', stats: '1,200ft up / 6,800ft down · ~5 Miles · 6-8 hrs', description: 'Summit Eldorado Peak at 8,868ft and ski directly off the summit — an unforgettable descent of massive glaciated terrain into Eldorado Creek. A grand finale to one of the finest ski circuits in the PNW.' },
    ],
    tags: ['ski-mountaineering', 'traverse'],
  },
  {
    id: 'steep-camp',
    title: 'Steep Camp',
    category: 'Ski & Splitboard',
    location: 'North Cascades, WA',
    duration: '3 Days',
    difficulty: 'Advanced',
    price: 975,
    spotsLeft: 5,
    season: 'Winter',
    image: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=1600&q=90',
    gallery: [],
    dates: ['January–March 2026', 'Multiple Dates'],
    ratio: '4:1',
    included: 'Instruction, group safety equipment, guide services',
    notIncluded: 'Personal gear, meals, transportation, lodging',
    shortDesc: 'Master steep and technical terrain with focused coaching from IFMGA guides. Small groups, maximum progression.',
    longDesc: 'Intro to Steep & Technical Riding is designed for advanced skiers and riders ready to push into more committing terrain with proper skills and safety knowledge.',
    itinerary: [],
    tags: ['steep-skiing', 'course'],
  },
  {
    id: 'aiare-level-1',
    title: 'AIARE Level 1 Avalanche Course',
    category: 'Avalanche',
    location: 'Washington Cascades',
    duration: '3 Days',
    difficulty: 'Beginner',
    price: 650,
    spotsLeft: 8,
    season: 'Winter',
    image: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=1600&q=90',
    gallery: [],
    dates: ['January–March 2026', 'Multiple Dates'],
    ratio: '4:1',
    included: 'Course materials, guide instruction, group safety gear',
    notIncluded: 'Personal avalanche beacon, probe, shovel, meals, lodging',
    shortDesc: 'The gold standard in recreational avalanche education. Learn to travel safely in avalanche terrain.',
    longDesc: 'The AIARE Level 1 is the most widely recognized avalanche course in North America, covering terrain assessment, snowpack evaluation, rescue techniques, and safe travel protocols.',
    itinerary: [],
    tags: ['avalanche', 'safety', 'course'],
  },
  {
    id: 'chamonix-climbing',
    title: 'Chamonix — French Alps Climbing',
    category: 'Alpine',
    location: 'Chamonix, France',
    duration: '8 Days',
    difficulty: 'Advanced',
    price: 3200,
    spotsLeft: 2,
    season: 'Summer',
    image: 'https://images.unsplash.com/photo-1502126324834-38f8e02d7160?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1502126324834-38f8e02d7160?w=1600&q=90',
    gallery: [],
    dates: ['July 5–12, 2026', 'August 2–9, 2026'],
    ratio: '2:1',
    included: 'Guide services, hut fees, group technical equipment',
    notIncluded: 'Flights, transfers, meals, personal gear, travel insurance (required)',
    shortDesc: "Climb classics in one of the world's greatest alpine playgrounds. Aiguilles, aretes, and glaciers with IFMGA guides.",
    longDesc: 'Climb the iconic routes of the Mont Blanc massif with IFMGA certified guides who know the range intimately.',
    itinerary: [],
    tags: ['alpine', 'international', 'climbing'],
  },
  {
    id: 'morning-star-peak',
    title: 'Morning Star Peak — Mile High Club',
    category: 'Rock',
    location: 'North Cascades, WA',
    duration: '1 Day',
    difficulty: 'Intermediate',
    price: 425,
    spotsLeft: 6,
    season: 'Summer',
    image: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=1600&q=90',
    gallery: [],
    dates: ['June–September 2026'],
    ratio: '2:1',
    included: 'Guide services, group climbing equipment, technical gear',
    notIncluded: 'Personal gear, meals, transportation',
    shortDesc: 'A stunning multi-pitch rock climb on beautiful Cascade granite. II+ 5.10a. One of the best moderate climbs in the range.',
    longDesc: 'The Mile High Club on Morning Star Peak is a classic North Cascades multi-pitch route on excellent granite with spectacular views of the surrounding peaks.',
    itinerary: [],
    tags: ['rock-climbing', 'multi-pitch'],
  },
  {
    id: 'alaska-ski-mo',
    title: 'Alaska Range Ski Mo Camp',
    category: 'Ski & Splitboard',
    location: 'Alaska Range, AK',
    duration: '10 Days',
    difficulty: 'Expert',
    price: 4800,
    spotsLeft: 4,
    season: 'Spring',
    image: 'https://images.unsplash.com/photo-1516592673884-4a382d1124c2?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1516592673884-4a382d1124c2?w=1600&q=90',
    gallery: [],
    dates: ['April 20–29, 2026'],
    ratio: '3:1',
    included: 'Fly-in, all meals, camp equipment, guide services',
    notIncluded: 'Flights to Anchorage, personal gear, travel insurance (required)',
    shortDesc: 'Glacier skiing in the heart of the Alaska Range. Big objectives, remote camps, unforgettable descents.',
    longDesc: 'An expedition-style ski mountaineering camp deep in the Alaska Range. Access glaciers by bush plane and ski massive remote terrain for 10 days.',
    itinerary: [],
    tags: ['ski-mountaineering', 'alaska', 'expedition'],
  },
]

export const guides = [
  {
    id: 'ian-nicholson',
    name: 'Ian Nicholson',
    title: 'IFMGA / AMGA Mountain Guide',
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&q=80',
    specialties: ['Alpine Climbing', 'Ski Mountaineering', 'Rock Climbing'],
    yearsGuiding: 20,
    bio: 'Ian has spent over two decades guiding in the Cascades, Alps, Andes, and ranges across the globe. He holds the highest international guiding certification (IFMGA) and has authored guidebooks to the region.',
    certifications: ['IFMGA', 'AMGA Rock', 'AMGA Alpine', 'AMGA Ski', 'WFR'],
    highlights: ['First ascents in the North Cascades', 'AMGA Guide Trainer', 'Published guidebook author'],
  },
  {
    id: 'matt-schonwald',
    name: 'Matt Schonwald',
    title: 'IFMGA / AMGA Mountain Guide',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80',
    specialties: ['Backcountry Skiing', 'Alpine Climbing', 'Avalanche Education'],
    yearsGuiding: 18,
    bio: 'Matt brings 18 years of high-altitude experience across four continents. A passionate educator, he trains guides through the AMGA and has led expeditions from Patagonia to the Himalayas.',
    certifications: ['IFMGA', 'AMGA Ski', 'AMGA Alpine', 'AIARE Pro', 'WFR'],
    highlights: ['Himalayan expedition leader', 'AMGA examiner', 'Avalanche educator'],
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Sarah K.',
    location: 'Seattle, WA',
    trip: 'Forbidden Tour',
    rating: 5,
    quote: "The Forbidden Tour was the single best week of my life. Ian and the team made an incredibly demanding route feel achievable. The views from Eldorado's summit brought me to tears.",
    image: 'https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=100&q=80',
  },
  {
    id: 2,
    name: 'Marcus T.',
    location: 'Portland, OR',
    trip: 'AIARE Level 1',
    rating: 5,
    quote: 'Matt is an exceptional educator. The AIARE course changed how I think about backcountry travel. Worth every penny — this knowledge could save your life.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
  },
  {
    id: 3,
    name: 'Julia R.',
    location: 'Denver, CO',
    trip: 'Chamonix Climbing',
    rating: 5,
    quote: 'Summiting in the French Alps with BCAG was a bucket list moment. The guides expertise and local knowledge made it both safe and deeply memorable.',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
  },
  {
    id: 4,
    name: 'David L.',
    location: 'San Francisco, CA',
    trip: 'Steep Camp',
    rating: 5,
    quote: "I've skied with a lot of guides over the years. BCAG is operating at a completely different level — technically, educationally, and in terms of the experience they create.",
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
  },
]

export const stats = [
  { value: '20+', label: 'Years Guiding' },
  { value: 'IFMGA', label: 'Certified Guides' },
  { value: '500+', label: 'Happy Clients' },
  { value: '4', label: 'Continents' },
]
